---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: wordpress
      tier: mysql
  template:
    metadata:
     labels:
      tier: mysql
      app: wordpress
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
               name: mysql-pass
               key: password   
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
       - name: mysql-persistent-storage
         persistentVolumeClaim:
           claimName: mysql-persistent-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-persistent-storage
  labels:
    app: wordpress
    tier: mysql
spec:
  storageClassName: manual
  accessModes:
      - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
 name: wordpress-mysql
 labels:
  app: wordpress
  tier: mysql
spec:
 ports:
   - port: 3306
 selector:
  app: wordpress
  tier: mysql
 clusterIP: None   










 
