---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-data
  labels:
     app: sonar-deployment
spec:
   storageClassName: manual
   accessModes:
    - ReadWriteOnce
   resources:
    requests:
       storage: 4Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonar-data
  labels:
      app: sonar-deployment
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  persistentVolumeReclaimPolicy: Recycle
  accessModes:
    - ReadWriteOnce
  hostPath: 
   path: "/opt/data"
      
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-ext
  labels:
     app: sonar-deployment
spec:
   storageClassName: manual
   accessModes:
    - ReadWriteOnce
   resources:
    requests:
       storage: 4Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonar-ext
  labels:
      app: sonar-deployment
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  persistentVolumeReclaimPolicy: Recycle
  accessModes:
    - ReadWriteOnce
  hostPath: 
   path: "/opt/extension"
      
