---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: {{ .Values.replicaCount }}
  template:
     metadata:
       labels:
          app: jenkins
     spec:
       containers:
         - name: jenkins
           image: {{ .Values.image.repository }}:{{ .Values.image.tag }} 
           env:
             - name: JAVA_OPTS
               value: -Djenkins.install.runSetupWizard=false
           ports:
             - name: http-port
               containerPort: 8080
             - name: jnlp-port
               containerPort: 50000
           volumeMounts:
             - name: jenkins-home
               mountPath: /data
       volumes:
       - name: jenkins-home
         persistentVolumeClaim:
            claimName: jenkins-home
