apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-persistence-volume-claim
spec:
  accessModes:
    - ReadWriteMany  
  resources:
    requests:
      storage: 5Gi
  storageClassName: azurefilestorage