apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-persistence-volume
  labels: 
    storage: slow
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteMany
  storageClassName: static-persistence-volume-storageclass
  azureFile:
    secretName: static-persistence-secret
    shareName: storage
    readOnly: false
  