apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sonar-mysql-deployment
  labels:
    app: sonar-mysql-deployment
spec:
  replicas: {{ .Values.replicaCount.mysql }}
  template:
    metadata:
      labels:
        app: sonar-mysql-deployment
    spec:
      containers:
      - image: {{ .Values.image.mysql.repository }}:{{ .Values.image.mysql.tag }}
        name: sonar-mysql-deployment
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: sonar
        - name: MYSQL_USER
          value: sonar
        - name: MYSQL_PASSWORD
          value: sonar
        volumeMounts:
         - name: mysql-data
           mountPath: /var/lib/mysql
      volumes:
      - name: mysql-data
        persitentVolumeClaim:
          claimName: mysql
