NFS Service in K8s

make sure nfs-utils and nfs-server package installed on master node

# yum install nfs-utils nfs-server -y 
# systemctl enable nfs-server
# systemctl status nfs-server

# mkdir -p /srv/nfs/kudedata
# chmod -R 777 /srv/nfs/kudedata
# vi /etc/exportfs
/srv/nfs/kubedata <nfs_ip>/24 or *(rw,sync,no_subtree_check,insecure)

# exportfs -v

copy the admin config from k8s master to nfs machine
# mkdir ~/.kube
# scp root@kubemaster:/etc/kubernetes/admin.conf ~/.kube/config

# kubectl cluster-info
# 

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: nginx
  name: nginx-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx
  template:
    metadata:
      labels:
        run: nginx
    spec:
      volumes:
      - name: www
        persistentVolumeClaim:
          claimName: pvc-nfs-pv1
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-pv1
  labels:
    type: local
    run: nginx
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: <nfs server ip>
    path: "/srv/nfs/kubedata"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-pv1
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi    

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
    run: nginx
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP


