# Default values for jenkins.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: jenkinsci/blueocean
  tag: latest

service:
  type: NodePort
  port: 8080
  targetport: 8080

