apiVersion: v1
kind: Secret
metadata:
  name: volume-azurefile-storage-secret
type: Opaque
data:
  azurestorageaccountname: [base64encodedStorageAccountName]
  azurestorageaccountkey: [base64encodedStorageAccountKey]