---
kind: Pod
apiVersion: v1
metadata:
  name: pod-uses-managed-slow
  labels:
    name: storage
spec:
  containers:
  - image: busybox
    name: az-c-01
    command:
    - "/bin/sh"
    - "-c"
    - while true; do echo $(date) >> /mnt/managed/outfile; sleep 1; done
    volumeMounts:
    - name: managed01
      mountPath: "/mnt/managed"
  volumes:
  - name: managed01
    persistentVolumeClaim:
      claimName: dd-managed-slow-01
