---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dd-managed-fast-01
  annotations:
    volume.beta.kubernetes.io/storage-class: managedfast
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 128Gi
