---
apiVersion: v1
kind: Config
preferences: {}

# Define the cluster
clusters:
- cluster:
  
    server: https://192.168.58.121:6443
  name: my-cluster

# Define the user
users:
- name: mynamespace-user
  user:
     as-user-extra: {}
     client-key-data: $ca
    token: $token

# Define the context : linking a user to a cluster
contexts:
- context:
    cluster: my-cluster
    namespace: mynamespace
    user: mynamespace-user
  name: mynamespace

# Define current context
current-context: mynamespace
