---
apiVersion: v1
clusters:
- cluster:
      certificate-authority-data: 
      server:
  name: mycluster
contexts
- context:
     cluster: mycluster
     namespace: dev
     user: dev-user
  name: dev-context
current-context: dev-context
kind: Config
preferences: {}
users:
- name: dev-user
  user:
     token :   
