kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nginx
  namespace: instavote
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccount: nginx-service-account
      containers:
      - image: nginx:latest
        name: nginx
        ports:
        - containerPort: 80
