apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    app: cassandra-dev
    pod: cassandra-svc
  name: cassandra-dev
spec:
  clusterIP: None
  ports:
  - port: 9042
  selector:
    app: cassandra-dev
    pod: cassandra
