# ## Server-2/7/8 local host path volumes:



---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-local-storage-server-2        # (1)
spec:
  capacity:
    storage: 100Gi                              # (2)
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain         # (3)
  storageClassName: cassandra-local-storage     # (4)
  hostPath:
    path: /var/lib/cassandra-dev                # (5)
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - server-2                            # (6)
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-local-storage-server-7
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cassandra-local-storage
  hostPath:
    path: /var/lib/cassandra-dev
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - server-7
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-local-storage-server-8
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cassandra-local-storage
  hostPath:
    path: /var/lib/cassandra-dev
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - server-8
