apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-persistence-storage
  labels:
     app: elasticsearch
     tier: frontend
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Recycle
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/pv1"
