apiVersion: v1
kind: Secret
metadata:
  name: kongcreds
  namespace: {{ .namespace }}
type: Opaque
data:
  username: usernameinbase64
  password: passinbase64
  postgresdbname: dbnameinbase64
#your secret in base64 echo -n 'admin' | base64 YWRtaW4=
